import type { Metadata } from "next";
import { Lora, Archivo, Libre_Baskerville } from "next/font/google";
import "@/styles/globals.css";
import Navigation from "@/components/General/Navigation";
import Footer from "@/components/Footer/Footer";

const ArchivoFont = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400"]
});

const LoraFont = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

const LibreBaskervilleFont = Libre_Baskerville({
  variable: "--font-libre-baskerville",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Biological knowledge",
  description: "Generated by create next app",
  authors: [{name: 'Ricardo Nava Hernandez'}],
  icons: {
    icon: [
      { url: "/favicon/favicon.ico" },
      { url: "/favicon/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/favicon/android-chrome-512x512.png", sizes: "512x512", type: "image/png" }
    ],
    apple: "/favicon/apple-touch-icon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="trancy-es">
      <body
        className={`${ArchivoFont.variable} ${LoraFont.variable} ${LibreBaskervilleFont.variable} font-Lora`}
      >
        <Navigation/>
        <div className="flex-1">
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
